import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import type { SqlConnectionConfig } from '../../shared/domain';
import { createTestApp, type TestApp } from '../helpers';
import { recordEvidence } from './evidence';
import { AWKWARD, runConformance, type EngineFixture } from './conformance';

/**
 * PostgreSQL, against an actual PostgreSQL server.
 *
 * Not PGlite. PGlite is PostgreSQL compiled to WebAssembly and linked into this process — genuine
 * `pg_catalog`, genuine SQL, and no server, no wire protocol, no `pg` driver, no authentication and
 * no socket. Those four are where connectors break in customer deployments, so a PGlite pass is
 * `ENGINE_COMPATIBLE` and this one is `ENGINE_VERIFIED`.
 *
 *   TEST_POSTGRES_URL=postgresql://postgres:pw@localhost:5432/db npm run test:engines
 *
 * Skipped without that variable, so an ordinary checkout is unaffected and a missing database can
 * never be mistaken for a pass.
 */

const URL_VAR = 'TEST_POSTGRES_URL';
const raw = process.env[URL_VAR];
const SCHEMA = 'dvm_conformance';

describe.skipIf(!raw)('PostgreSQL conformance against a real server', () => {
  let t: TestApp;
  let pool: import('pg').Pool;

  beforeAll(async () => {
    t = await createTestApp();
    const { Pool } = await import('pg');
    pool = new Pool({ connectionString: raw, max: 4 });
  }, 120_000);

  afterAll(async () => {
    await pool?.end().catch(() => undefined);
    await t?.close();
  });

  it('drives the production connector through the pg driver', async () => {
    const url = new URL(raw!);
    const config: SqlConnectionConfig = {
      host: url.hostname,
      port: Number(url.port) || 5432,
      database: decodeURIComponent(url.pathname.replace(/^\//, '')),
      authType: 'SQL_LOGIN',
      username: decodeURIComponent(url.username),
      encrypt: false,
      trustServerCertificate: true,
      transport: 'DIRECT',
      schemas: [SCHEMA],
    };

    const evidence = await runConformance(
      {
        type: 'POSTGRES',
        engine: 'postgresql',
        config,
        password: decodeURIComponent(url.password),
        provision: () => provision(pool),
        teardown: async () => {
          await pool.query(`DROP SCHEMA IF EXISTS ${SCHEMA} CASCADE`);
        },
      },
      (type, cfg, password) => t.services.connections.sqlConnectorFor(type, cfg, password),
      'tests/engines/postgres.engine.test.ts',
    );

    // The suite returns only what it proved; anything it did not reach is simply absent.
    expect(evidence.capabilities.connect).toBe('PASSED');
    expect(evidence.capabilities.schemaDiscovery).toBe('PASSED');
    expect(evidence.capabilities.write).toBe('PASSED');
    expect(evidence.serverVersion, 'the server named itself').toMatch(/PostgreSQL/i);
    await recordEvidence(evidence);
  }, 300_000);
});

/**
 * The fixture, built with the raw driver before the connector sees any of it.
 *
 * That ordering is deliberate: the connector is then describing rows it did not create, so a
 * connector that invented its answers would disagree with what is actually in the database.
 */
async function provision(pool: import('pg').Pool): Promise<EngineFixture> {
  const { rows: version } = await pool.query<{ v: string }>('SELECT version() AS v');
  await pool.query(`DROP SCHEMA IF EXISTS ${SCHEMA} CASCADE`);
  await pool.query(`CREATE SCHEMA ${SCHEMA}`);
  await pool.query(`
    CREATE TABLE ${SCHEMA}.people (
      person_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code        varchar(40) NOT NULL,
      full_name   varchar(200) NOT NULL,
      nickname    varchar(60),
      balance     numeric(18,4),
      joined_at   timestamp,
      joined_tz   timestamptz,
      is_active   boolean NOT NULL DEFAULT true,
      big_number  bigint,
      external_id uuid,
      notes       text,
      "order"     integer,
      "MixedCase" varchar(40)
    )`);
  await pool.query(`
    CREATE TABLE ${SCHEMA}.visits (
      visit_id  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      person_id integer NOT NULL REFERENCES ${SCHEMA}.people(person_id),
      seen_on   date NOT NULL
    )`);
  // An empty table for the write half, so writing never disturbs what reading asserts.
  await pool.query(`
    CREATE TABLE ${SCHEMA}.arrivals (
      arrival_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      code       varchar(40) NOT NULL,
      full_name  varchar(200) NOT NULL,
      nickname   varchar(60),
      balance    numeric(18,4),
      notes      text
    )`);

  // Deterministic, and chosen to be awkward: Unicode, emoji, an empty string, quotes and
  // backslashes, a null, a value at the edge of an exact integer, long text, and a repeated code.
  const people: [string, string, string | null, string | null, number | null, string][] = [
    ['P-001', AWKWARD.unicode, null, AWKWARD.decimal, AWKWARD.bigInteger, AWKWARD.longText],
    ['P-002', AWKWARD.specialChars, AWKWARD.emptyString, '0.0001', 0, 'short'],
    ['P-003', 'Plain Name', 'plain', '-99.5000', -1, ''],
    ['DUP-9', 'First Duplicate', 'one', '1.0000', 1, 'a'],
    ['DUP-9', 'Second Duplicate', 'two', '2.0000', 2, 'b'],
    ['DUP-9', 'Third Duplicate', null, '3.0000', 3, 'c'],
    ['P-007', 'Seventh', 'seven', null, null, 'd'],
  ];
  for (const [code, name, nickname, balance, big, notes] of people) {
    await pool.query(
      `INSERT INTO ${SCHEMA}.people (code, full_name, nickname, balance, joined_at, joined_tz, big_number, external_id, notes, "order", "MixedCase")
       VALUES ($1,$2,$3,$4, timestamp '2026-03-01 12:34:56', timestamptz '2026-03-01 12:34:56+05:30', $5, gen_random_uuid(), $6, 7, 'Mixed')`,
      [code, name, nickname, balance, big, notes],
    );
  }
  await pool.query(
    `INSERT INTO ${SCHEMA}.visits (person_id, seen_on)
     SELECT person_id, date '2026-04-01' FROM ${SCHEMA}.people LIMIT 3`,
  );

  return {
    serverVersion: version[0]!.v,
    peopleTable: `${SCHEMA}.people`,
    visitsTable: `${SCHEMA}.visits`,
    targetTable: `${SCHEMA}.arrivals`,
    peopleRows: people.length,
    duplicateKeyColumn: 'code',
    duplicateOccurrences: 3,
  };
}
