import { sql } from 'drizzle-orm';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import {
  buildTableMetadata,
  buildTableSummaries,
  type SqlColumnRow,
  type SqlFkRow,
  type SqlPkRow,
  type SqlTableRow,
  type SqlUniqueRow,
} from '../../server/src/connectors/sql/catalog';
import {
  PG_COLUMNS_QUERY,
  PG_FOREIGN_KEYS_QUERY,
  PG_PRIMARY_KEYS_QUERY,
  PG_TABLES_QUERY,
  PG_UNIQUE_KEYS_QUERY,
} from '../../server/src/connectors/sql/postgres-catalog';
import { PG_TYPES } from '../../server/src/connectors/sql/postgres-connector';
import { createTestApp, type TestApp } from '../helpers';

/**
 * The PostgreSQL catalog queries, run against PostgreSQL.
 *
 * PGlite is real PostgreSQL compiled to WebAssembly, so `pg_catalog` behaves exactly as it does on a
 * server. That makes this the test that matters: a connector's discovery is only as good as its
 * catalog queries, and a query that is subtly wrong produces plausible metadata rather than an
 * error — a column silently typed `Other`, a foreign key that never becomes a lookup, a serial
 * column the migration then tries to write to.
 */
/**
 * The fixture database. Deliberately awkward: an identity column and a serial one, a generated
 * column, a full unique index and a partial one, a composite primary key, a view, and the types
 * whose meaning differs between PostgreSQL and SQL Server.
 */
const SCHEMA = [
  `CREATE SCHEMA sales`,
  `CREATE TABLE sales.region (
     region_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name      varchar(60) NOT NULL,
     code      char(3)
   )`,
  `CREATE TABLE sales.customer (
     customer_id  bigserial PRIMARY KEY,
     account_no   varchar(20) NOT NULL,
     display_name varchar(160) NOT NULL,
     notes        text,
     credit_limit numeric(12,2) DEFAULT 0,
     employees    integer,
     is_active    boolean NOT NULL DEFAULT true,
     created_at   timestamptz NOT NULL DEFAULT now(),
     modified_at  timestamp,
     birth_date   date,
     external_id  uuid,
     payload      jsonb,
     picture      bytea,
     region_id    integer REFERENCES sales.region(region_id),
     full_label   text GENERATED ALWAYS AS (display_name || ' (' || account_no || ')') STORED
   )`,
  // A real alternate key, and a partial one that must never be treated as one.
  `CREATE UNIQUE INDEX customer_account_no_uq ON sales.customer (account_no)`,
  `CREATE UNIQUE INDEX customer_active_name_uq ON sales.customer (display_name) WHERE is_active`,
  // A composite primary key: no single column identifies a row.
  `CREATE TABLE sales.order_line (
     order_id integer NOT NULL,
     line_no  integer NOT NULL,
     sku      varchar(40) NOT NULL,
     PRIMARY KEY (order_id, line_no)
   )`,
  `CREATE VIEW sales.active_customer AS
     SELECT customer_id, display_name FROM sales.customer WHERE is_active`,
];

describe('postgres catalog discovery', () => {
  let t: TestApp;
  let tables: SqlTableRow[];
  let columns: SqlColumnRow[];
  let primaryKeys: SqlPkRow[];
  let uniques: SqlUniqueRow[];
  let foreignKeys: SqlFkRow[];

  const rows = async <T>(query: string): Promise<T[]> => {
    const result = await t.services.db.execute(sql.raw(query));
    return (result as unknown as { rows: T[] }).rows;
  };

  beforeAll(async () => {
    t = await createTestApp();
    // A schema exercising the things a real database has and a naive query gets wrong.
    // One statement per call: a prepared statement holds exactly one.
    for (const statement of SCHEMA) await t.services.db.execute(sql.raw(statement));

    [tables, columns, primaryKeys, uniques, foreignKeys] = await Promise.all([
      rows<SqlTableRow>(PG_TABLES_QUERY),
      rows<SqlColumnRow>(PG_COLUMNS_QUERY),
      rows<SqlPkRow>(PG_PRIMARY_KEYS_QUERY),
      rows<SqlUniqueRow>(PG_UNIQUE_KEYS_QUERY),
      rows<SqlFkRow>(PG_FOREIGN_KEYS_QUERY),
    ]);
  });
  afterAll(async () => {
    await t.close();
  });

  const tableRow = (schema: string, name: string) =>
    tables.find((r) => r.schemaName === schema && r.tableName === name)!;

  const metaFor = (schema: string, name: string) =>
    buildTableMetadata(
      { table: tableRow(schema, name), columns, primaryKeys, uniques, foreignKeys },
      PG_TYPES,
    );

  // ---------------------------------------------------------------------------

  it('finds tables and views, and leaves the system catalogs alone', () => {
    const names = tables.map((r) => `${r.schemaName}.${r.tableName}`);
    expect(names).toContain('sales.customer');
    expect(names).toContain('sales.region');
    expect(names).toContain('sales.order_line');
    expect(names).toContain('sales.active_customer');
    // Nothing from PostgreSQL's own schemas: a catalogue full of pg_* would drown the real tables.
    expect(names.some((n) => n.startsWith('pg_catalog.') || n.startsWith('information_schema.'))).toBe(false);
    expect(tableRow('sales', 'active_customer').objectType).toBe('view');
    expect(tableRow('sales', 'customer').objectType).toBe('table');

    const summaries = buildTableSummaries(tables);
    const view = summaries.find((s) => s.logicalName === 'sales.active_customer')!;
    // A view is marked as one, which is what stops it being offered as a migration target.
    expect(view.isView).toBe(true);
    expect(summaries.find((s) => s.logicalName === 'sales.customer')!.isView).toBe(false);
  });

  it('types every column the way PostgreSQL means it', () => {
    const meta = metaFor('sales', 'customer');
    const byName = new Map(meta.attributes.map((a) => [a.logicalName, a]));

    expect(byName.get('display_name')).toMatchObject({ type: 'String', maxLength: 160 });
    expect(byName.get('account_no')).toMatchObject({ type: 'String', maxLength: 20 });
    // Unbounded text is a memo, and has no length to report rather than a made-up one.
    expect(byName.get('notes')).toMatchObject({ type: 'Memo', maxLength: null });
    expect(byName.get('credit_limit')).toMatchObject({ type: 'Decimal', precision: 2 });
    expect(byName.get('employees')!.type).toBe('Integer');
    expect(byName.get('customer_id')!.type).toBe('BigInt');
    expect(byName.get('is_active')!.type).toBe('Boolean');
    expect(byName.get('external_id')!.type).toBe('Uniqueidentifier');
    expect(byName.get('payload')!.type).toBe('Memo');

    // The one that a shared type table would have got wrong: in PostgreSQL `timestamp` is a point in
    // time, not a row version, so it must be a migratable DateTime.
    expect(byName.get('modified_at')).toMatchObject({
      type: 'DateTime',
      dateTimeBehavior: 'TimeZoneIndependent',
    });
    expect(byName.get('created_at')).toMatchObject({
      type: 'DateTime',
      dateTimeBehavior: 'UserLocal',
    });
    expect(byName.get('birth_date')).toMatchObject({ type: 'DateTime', dateTimeBehavior: 'DateOnly' });

    // Integer ranges come from the real widths, so a range check is not a guess.
    expect(byName.get('employees')).toMatchObject({ minValue: -2_147_483_648, maxValue: 2_147_483_647 });
    // char(3) reports 3 characters: PostgreSQL already counts characters, unlike SQL Server's bytes.
    expect(metaFor('sales', 'region').attributes.find((a) => a.logicalName === 'code')!.maxLength).toBe(3);
  });

  it('knows which columns the server writes for itself', () => {
    const meta = metaFor('sales', 'customer');
    const byName = new Map(meta.attributes.map((a) => [a.logicalName, a]));

    // bigserial is a default of nextval(...), not a declared identity — mistaking it for a writable
    // column would make the migration supply its own keys and collide with the sequence.
    expect(byName.get('customer_id')!.sql?.isIdentity).toBe(true);
    expect(byName.get('customer_id')!.isValidForCreate).toBe(false);
    // GENERATED … AS IDENTITY, the SQL-standard form.
    expect(
      metaFor('sales', 'region').attributes.find((a) => a.logicalName === 'region_id')!.sql?.isIdentity,
    ).toBe(true);
    // A generated column is computed: it can be read, never written.
    expect(byName.get('full_label')!.sql?.isComputed).toBe(true);
    expect(byName.get('full_label')!.isValidForCreate).toBe(false);
    expect(byName.get('full_label')!.isValidForRead).toBe(true);
    // PostgreSQL has no row version, and saying it did would exclude real columns.
    expect(meta.attributes.every((a) => a.sql?.isRowVersion === false)).toBe(true);

    // NOT NULL with a default is not required of the source: the server fills it in.
    expect(byName.get('is_active')!.requiredLevel).toBe('None');
    expect(byName.get('display_name')!.requiredLevel).toBe('ApplicationRequired');
    expect(byName.get('notes')!.requiredLevel).toBe('None');
  });

  it('turns a foreign key into a lookup at the referenced table', () => {
    const meta = metaFor('sales', 'customer');
    const region = meta.attributes.find((a) => a.logicalName === 'region_id')!;
    expect(region.type).toBe('Lookup');
    expect(region.targets).toEqual(['sales.region']);
    expect(meta.manyToOne.map((r) => r.referencedEntity)).toContain('sales.region');
  });

  it('publishes a real alternate key and refuses a partial one', () => {
    const meta = metaFor('sales', 'customer');
    const byName = new Map(meta.keys.map((k) => [k.logicalName, k]));

    const full = byName.get('customer_account_no_uq')!;
    expect(full.attributes).toEqual(['account_no']);
    expect(full.status).toBe('Active');

    // A unique index with a WHERE clause only enforces uniqueness over part of the table, so it
    // cannot be trusted to identify a record. It is reported, and reported as unusable.
    const partial = byName.get('customer_active_name_uq')!;
    expect(partial.status).toBe('Filtered');
  });

  it('refuses to invent a primary id for a composite key', () => {
    const line = metaFor('sales', 'order_line');
    // Two columns identify a row, so no single column is the record's id. Pretending otherwise
    // would silently match records on half a key.
    expect(line.attributes.filter((a) => a.isPrimaryId)).toEqual([]);
    const key = line.keys.find((k) => k.attributes.length === 2)!;
    expect(key.attributes).toEqual(['order_id', 'line_no']);

    const customer = metaFor('sales', 'customer');
    expect(customer.primaryIdAttribute).toBe('customer_id');
    expect(customer.attributes.find((a) => a.isPrimaryId)!.logicalName).toBe('customer_id');
  });

  it('picks a display column that reads like a name, and never a key or a blob', () => {
    expect(metaFor('sales', 'customer').primaryNameAttribute).toBe('display_name');
    expect(metaFor('sales', 'region').primaryNameAttribute).toBe('name');
  });

  it('reports a row estimate rather than a count', () => {
    // reltuples is the planner's estimate, which is why a count from it is flagged approximate.
    // Freshly created tables have never been analyzed, so the estimate is unknown rather than zero.
    const customer = tableRow('sales', 'customer');
    expect(customer.rowCount === null || Number(customer.rowCount) >= 0).toBe(true);
  });
});
