import { and, eq } from 'drizzle-orm';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import type {
  EnvironmentDto,
  MigrationPlanDto,
  MigrationRunDto,
  PreflightRunDto,
  ValidationRunDto,
} from '../../shared/domain';
import { demoRecords } from '../../server/src/db/schema';
import { ApiClient, createTestApp, type TestApp } from '../helpers';

/**
 * The headline cross-provider journey: a legacy SQL Server database migrated into Dataverse.
 *
 * It exercises the whole chain — SQL discovery, table mapping, field mapping, choice mapping,
 * foreign key to lookup resolution through the record identity map, preflight, execution,
 * the zero-write guarantee on a second run, and validation of the transformed values.
 */
describe('SQL Server → Dataverse', () => {
  let t: TestApp;
  let api: ApiClient;
  let sqlConn: EnvironmentDto;
  let qa: EnvironmentDto;
  let worker: ReturnType<TestApp['services']['createWorker']>;
  let plan: MigrationPlanDto;

  beforeAll(async () => {
    t = await createTestApp();
    api = new ApiClient(t.app);
    worker = t.services.createWorker();
    await api.demoLogin();
    const envs = await api.post<EnvironmentDto[]>('/api/environments/discover');
    sqlConn = envs.find((e) => e.connectionType === 'SQL_SERVER')!;
    qa = envs.find((e) => e.displayName === 'DeepTrics QA')!;
  });
  afterAll(async () => {
    await worker.stop();
    await t.close();
  });

  const entityOf = (p: MigrationPlanDto, table: string) => p.entities.find((e) => e.logicalName === table)!;

  const mapField = async (table: string, sourceField: string, targetField: string) => {
    const entity = entityOf(plan, table);
    const { mappings } = await api.get<{ mappings: { id: string; sourceField: string }[] }>(
      `/api/plans/${plan.id}/entities/${entity.id}/mappings`,
    );
    const mapping = mappings.find((m) => m.sourceField === sourceField)!;
    plan = await api.patch<MigrationPlanDto>(`/api/plans/${plan.id}/mappings/${mapping.id}`, {
      action: 'MAP',
      targetField,
    });
    return mapping.id;
  };

  it('discovers the SQL connection with its capabilities', () => {
    expect(sqlConn).toBeDefined();
    expect(sqlConn.connectionType).toBe('SQL_SERVER');
    expect(sqlConn.sql).toMatchObject({ database: 'IIC_Legacy', port: 1433 });
    // SQL has no ownership or impersonated attribution, and the UI reads that from here.
    expect(sqlConn.capabilities).toMatchObject({
      supportsRead: true,
      supportsWrite: true,
      supportsTransactions: true,
      supportsOwnership: false,
      supportsAuditImpersonation: false,
      supportsChoices: false,
    });
  });

  it('discovers SQL tables, columns, keys and foreign keys', async () => {
    const tables = await api.get<{ logicalName: string; displayName: string }[]>(
      `/api/environments/${sqlConn.id}/tables`,
    );
    const names = tables.map((x) => x.logicalName);
    expect(names).toEqual(
      expect.arrayContaining([
        'dbo.Customer',
        'dbo.Contact',
        'dbo.Order',
        'dbo.OrderLine',
        'dbo.Product',
        'config.Region',
        'config.ApplicationSetting',
      ]),
    );

    const customer = await api.get<{
      primaryIdAttribute: string;
      attributes: {
        logicalName: string;
        type: string;
        isValidForCreate: boolean;
        targets?: string[];
        sql?: { isIdentity: boolean; dataType: string };
      }[];
      keys: { logicalName: string; attributes: string[] }[];
      manyToOne: { referencingAttribute: string; referencedEntity: string }[];
    }>(`/api/environments/${sqlConn.id}/tables/dbo.Customer`);

    expect(customer.primaryIdAttribute).toBe('CustomerId');
    const byName = new Map(customer.attributes.map((a) => [a.logicalName, a]));
    // An identity column is generated by the database and is never written by a migration.
    expect(byName.get('CustomerId')!.sql!.isIdentity).toBe(true);
    expect(byName.get('CustomerId')!.isValidForCreate).toBe(false);
    // A foreign key is surfaced as a lookup so the shared engine resolves it like any other.
    expect(byName.get('RegionId')!.type).toBe('Lookup');
    expect(byName.get('RegionId')!.targets).toEqual(['config.Region']);
    expect(customer.manyToOne.some((r) => r.referencedEntity === 'config.Region')).toBe(true);
    expect(customer.keys.map((k) => k.logicalName)).toContain('UQ_Customer_CustomerNumber');
  });

  it('pairs SQL tables with Dataverse tables, but never without confirmation', async () => {
    plan = await api.post<MigrationPlanDto>('/api/plans', {
      name: 'Legacy SQL to QA',
      sourceEnvironmentId: sqlConn.id,
      targetEnvironmentId: qa.id,
      tables: ['config.Region', 'dbo.Customer', 'dbo.Contact'],
    });
    // Sync so a re-run updates what changed and leaves everything else untouched.
    plan = await api.patch<MigrationPlanDto>(`/api/plans/${plan.id}/options`, {
      conflictStrategy: 'SYNC',
    });

    // config.Region -> dtx_region is suggested by name, and suggestions block execution.
    const region = entityOf(plan, 'config.Region');
    expect(region.objectMappingStatus).toBe('AUTO_SUGGESTED');
    expect(region.targetLogicalName).toBe('dtx_region');
    expect(plan.issues.some((i) => i.code === 'OBJECT_MAPPING_UNCONFIRMED')).toBe(true);
    expect(plan.blockerCount).toBeGreaterThan(0);

    const candidates = await api.get<{
      candidates: { logicalName: string; confidence: number }[];
      allTargets: { logicalName: string }[];
    }>(`/api/plans/${plan.id}/entities/${entityOf(plan, 'dbo.Customer').id}/target-candidates`);
    expect(candidates.candidates.map((c) => c.logicalName)).toContain('account');
    expect(candidates.allTargets.length).toBeGreaterThan(3);

    for (const [table, target] of [
      ['config.Region', 'dtx_region'],
      ['dbo.Customer', 'account'],
      ['dbo.Contact', 'contact'],
    ] as const) {
      plan = await api.patch<MigrationPlanDto>(
        `/api/plans/${plan.id}/entities/${entityOf(plan, table).id}/object-mapping`,
        { targetLogicalName: target, status: 'CONFIRMED' },
      );
    }
    expect(entityOf(plan, 'dbo.Customer').targetLogicalName).toBe('account');
    expect(plan.issues.some((i) => i.code === 'OBJECT_MAPPING_UNCONFIRMED')).toBe(false);
  });

  it('maps columns across providers and reports type compatibility', async () => {
    await mapField('config.Region', 'RegionName', 'dtx_name');
    await mapField('config.Region', 'RegionCode', 'dtx_code');

    await mapField('dbo.Customer', 'CustomerName', 'name');
    await mapField('dbo.Customer', 'CustomerNumber', 'accountnumber');
    await mapField('dbo.Customer', 'Email', 'emailaddress1');
    await mapField('dbo.Customer', 'Phone', 'telephone1');
    await mapField('dbo.Customer', 'CreditLimit', 'revenue');
    await mapField('dbo.Customer', 'EmployeeCount', 'numberofemployees');
    await mapField('dbo.Customer', 'OnCreditHold', 'creditonhold');
    await mapField('dbo.Customer', 'Notes', 'description');
    // A SQL foreign key mapped onto a Dataverse lookup: resolved through the identity map.
    await mapField('dbo.Customer', 'RegionId', 'dtx_regionid');
    // 200 characters of source into a 100 character target column.
    await mapField('dbo.Customer', 'Website', 'websiteurl');

    await mapField('dbo.Contact', 'FirstName', 'firstname');
    await mapField('dbo.Contact', 'LastName', 'lastname');
    await mapField('dbo.Contact', 'Email', 'emailaddress1');
    await mapField('dbo.Contact', 'CustomerId', 'parentcustomerid');

    const entity = entityOf(plan, 'dbo.Customer');
    const { mappings } = await api.get<{
      mappings: { sourceField: string; targetField: string | null; compatibility: string; status: string }[];
    }>(`/api/plans/${plan.id}/entities/${entity.id}/mappings`);
    const byField = new Map(mappings.map((m) => [m.sourceField, m]));
    // nvarchar(20) into a 20 character column fits exactly.
    expect(byField.get('CustomerNumber')!.compatibility).toBe('COMPATIBLE');
    // A wider source column than the target can truncate, and the plan says so up front.
    expect(byField.get('CustomerName')!.compatibility).toBe('LOSSY');
    expect(byField.get('Website')!.compatibility).toBe('LOSSY');
    expect(plan.issues.some((i) => i.code === 'LOSSY_CONVERSION')).toBe(true);
    // An integer foreign key can be mapped onto a lookup: the key itself is translated by the
    // record identity map, which the migration below proves.
    expect(byField.get('RegionId')!.compatibility).not.toBe('INCOMPATIBLE');
    expect(byField.get('RegionId')!.status).toBe('MANUAL');
  });

  it('requires a choice mapping for a text column going into a Dataverse choice', async () => {
    const mappingId = await mapField('dbo.Customer', 'Industry', 'industrycode');
    expect(plan.issues.some((i) => i.code === 'CHOICE_MAPPING_MISSING')).toBe(true);
    expect(plan.blockerCount).toBeGreaterThan(0);

    const entity = entityOf(plan, 'dbo.Customer');
    const profile = await api.get<{ values: { value: string; occurrences: number }[] }>(
      `/api/plans/${plan.id}/entities/${entity.id}/values/Industry`,
    );
    const values = profile.values.map((v) => v.value);
    expect(values).toContain('Manufacturing');
    // The value nobody planned for is visible before the migration, not after.
    expect(values).toContain('Aerospace');

    const target = await api.get<{
      attributes: { logicalName: string; options?: { value: number; label: string }[] }[];
    }>(`/api/environments/${qa.id}/tables/account`);
    const options = target.attributes.find((a) => a.logicalName === 'industrycode')!.options!;
    const optionFor = (label: string) => options.find((o) => o.label === label)?.value ?? null;

    plan = await api.patch<MigrationPlanDto>(`/api/plans/${plan.id}/mappings/${mappingId}/choice-map`, {
      entries: values.map((value) => ({
        sourceValue: value,
        targetValue: optionFor(value),
        targetLabel: optionFor(value) === null ? null : value,
        status: optionFor(value) === null ? ('UNMAPPED' as const) : ('CONFIRMED' as const),
      })),
      defaultTargetValue: null,
    });
    // Aerospace has no matching choice in QA, so the plan still blocks.
    expect(plan.issues.some((i) => i.code === 'CHOICE_MAPPING_INCOMPLETE')).toBe(true);

    plan = await api.patch<MigrationPlanDto>(`/api/plans/${plan.id}/mappings/${mappingId}/choice-map`, {
      entries: values.map((value) => ({
        sourceValue: value,
        targetValue: optionFor(value),
        targetLabel: optionFor(value) === null ? null : value,
        // The unmatched value is excluded explicitly, which is a decision, not a guess.
        status: optionFor(value) === null ? ('IGNORED' as const) : ('CONFIRMED' as const),
      })),
      defaultTargetValue: null,
    });
    expect(plan.issues.some((i) => i.code === 'CHOICE_MAPPING_INCOMPLETE')).toBe(false);
  });

  it('orders tables by their foreign keys and matches on a business key', async () => {
    // config.Region is referenced by dbo.Customer, so it migrates first.
    const region = entityOf(plan, 'config.Region');
    const customer = entityOf(plan, 'dbo.Customer');
    const contact = entityOf(plan, 'dbo.Contact');
    expect(region.orderIndex).toBeLessThan(customer.orderIndex);
    expect(customer.orderIndex).toBeLessThan(contact.orderIndex);
    expect(customer.dependsOn.some((d) => d.to === 'config.Region')).toBe(true);

    // A SQL identity key cannot be carried into Dataverse, so records are matched on a key.
    plan = await api.patch<MigrationPlanDto>(`/api/plans/${plan.id}/entities/${customer.id}`, {
      matchStrategy: 'BUSINESS_KEY',
      alternateKey: null,
      businessKeyFields: ['accountnumber'],
    });
    plan = await api.patch<MigrationPlanDto>(`/api/plans/${plan.id}/entities/${region.id}`, {
      matchStrategy: 'BUSINESS_KEY',
      alternateKey: null,
      businessKeyFields: ['dtx_code'],
    });
    plan = await api.patch<MigrationPlanDto>(`/api/plans/${plan.id}/entities/${contact.id}`, {
      matchStrategy: 'BUSINESS_KEY',
      alternateKey: null,
      businessKeyFields: ['emailaddress1'],
    });
    expect(plan.blockerCount).toBe(0);
  });

  let preflight: PreflightRunDto;
  it('preflights the cross-provider migration without writing anything', async () => {
    const before = await t.services.db
      .select()
      .from(demoRecords)
      .where(and(eq(demoRecords.environmentKey, 'demo-qa'), eq(demoRecords.logicalName, 'dtx_region')));

    const started = await api.post<PreflightRunDto>(`/api/plans/${plan.id}/preflight`);
    await worker.drain(180_000);
    preflight = await api.get<PreflightRunDto>(`/api/preflight/${started.id}`);
    expect(preflight.status).toBe('COMPLETED');

    expect(preflight.totals.sourceRecords).toBe(4 + 26 + 40);
    expect(preflight.totals.create).toBeGreaterThan(60);
    // Two source customers share a customer number: neither is written on a guess.
    expect(preflight.totals.conflict + preflight.totals.blocked).toBeGreaterThan(0);

    const after = await t.services.db
      .select()
      .from(demoRecords)
      .where(and(eq(demoRecords.environmentKey, 'demo-qa'), eq(demoRecords.logicalName, 'dtx_region')));
    expect(after.length).toBe(before.length);
  });

  let run: MigrationRunDto;
  it('migrates SQL rows into Dataverse, resolving foreign keys to lookups', async () => {
    const started = await api.post<MigrationRunDto>(`/api/plans/${plan.id}/execute`, {
      confirmSourceName: sqlConn.displayName,
      confirmTargetName: qa.displayName,
      acknowledgeWarnings: true,
    });
    await worker.drain(180_000);
    run = await api.get<MigrationRunDto>(`/api/runs/${started.id}`);
    expect(['COMPLETED', 'COMPLETED_WITH_ERRORS']).toContain(run.status);
    expect(run.created).toBeGreaterThan(60);

    // A migrated account carries the values the mapping promised, and its region lookup points
    // at the Dataverse record that the SQL region row became.
    const records = await api.get<{ items: { sourceId: string; targetId: string; entity: string }[] }>(
      `/api/runs/${run.id}/records?entity=dbo.Customer&limit=100`,
    );
    const first = records.items.find((r) => r.targetId)!;
    const [sourceRow] = await t.services.db
      .select()
      .from(demoRecords)
      .where(
        and(
          eq(demoRecords.environmentKey, 'demo-sql'),
          eq(demoRecords.logicalName, 'dbo.Customer'),
          eq(demoRecords.recordId, first.sourceId),
        ),
      );
    const [targetRow] = await t.services.db
      .select()
      .from(demoRecords)
      .where(
        and(
          eq(demoRecords.environmentKey, 'demo-qa'),
          eq(demoRecords.logicalName, 'account'),
          eq(demoRecords.recordId, first.targetId.toLowerCase()),
        ),
      );
    const source = sourceRow.data as Record<string, unknown>;
    const target = targetRow.data as Record<string, unknown>;
    expect(target.name).toBe(source.CustomerName);
    expect(target.accountnumber).toBe(source.CustomerNumber);

    if (source.RegionId) {
      const regionLink = target.dtx_regionid as { id: string } | null;
      expect(regionLink).toBeTruthy();
      // The Dataverse id is not the SQL integer: it came from the record identity map.
      expect(regionLink!.id).not.toBe(String(source.RegionId));
      const [regionRow] = await t.services.db
        .select()
        .from(demoRecords)
        .where(
          and(
            eq(demoRecords.environmentKey, 'demo-qa'),
            eq(demoRecords.logicalName, 'dtx_region'),
            eq(demoRecords.recordId, regionLink!.id.toLowerCase()),
          ),
        );
      expect(regionRow).toBeTruthy();
    }
  });

  it('writes nothing at all when the same migration runs again', async () => {
    const pf = await api.post<PreflightRunDto>(`/api/plans/${plan.id}/preflight`);
    await worker.drain(180_000);
    const second = await api.get<PreflightRunDto>(`/api/preflight/${pf.id}`);
    // The two source rows sharing a customer number stay a conflict, and the row whose website
    // is too long for the target column stays blocked: neither is quietly written.
    const blocked = await api.get<{ items: { reasonCode: string }[] }>(
      `/api/preflight/${second.id}/records?action=BLOCKED`,
    );
    expect(blocked.items.map((b) => b.reasonCode)).toContain('STRING_TOO_LONG');
    expect(second.totals.create).toBe(0);
    expect(second.totals.update).toBe(0);
    expect(second.totals.unchanged).toBeGreaterThan(60);

    const before = await t.services.db
      .select()
      .from(demoRecords)
      .where(and(eq(demoRecords.environmentKey, 'demo-qa'), eq(demoRecords.logicalName, 'account')));

    const started = await api.post<MigrationRunDto>(`/api/plans/${plan.id}/execute`, {
      confirmSourceName: sqlConn.displayName,
      confirmTargetName: qa.displayName,
      acknowledgeWarnings: true,
    });
    await worker.drain(180_000);
    const again = await api.get<MigrationRunDto>(`/api/runs/${started.id}`);
    expect(again.created).toBe(0);
    expect(again.updated).toBe(0);
    expect(again.unchanged).toBeGreaterThan(60);

    const after = await t.services.db
      .select()
      .from(demoRecords)
      .where(and(eq(demoRecords.environmentKey, 'demo-qa'), eq(demoRecords.logicalName, 'account')));
    expect(after.length).toBe(before.length);
    // Not one stored row changed, so no target audit stamp moved either.
    expect(JSON.stringify(after.map((r) => r.data))).toBe(JSON.stringify(before.map((r) => r.data)));
  });

  it('updates exactly one record after one SQL row changes', async () => {
    const [row] = await t.services.db
      .select()
      .from(demoRecords)
      .where(and(eq(demoRecords.environmentKey, 'demo-sql'), eq(demoRecords.logicalName, 'config.Region')));
    const data = row.data as Record<string, unknown>;
    await t.services.db
      .update(demoRecords)
      .set({ data: { ...data, RegionName: 'Renamed in the legacy database' } })
      .where(
        and(
          eq(demoRecords.environmentKey, 'demo-sql'),
          eq(demoRecords.logicalName, 'config.Region'),
          eq(demoRecords.recordId, row.recordId),
        ),
      );

    const pf = await api.post<PreflightRunDto>(`/api/plans/${plan.id}/preflight`);
    await worker.drain(180_000);
    const preview = await api.get<PreflightRunDto>(`/api/preflight/${pf.id}`);
    expect(preview.totals.update).toBe(1);

    const started = await api.post<MigrationRunDto>(`/api/plans/${plan.id}/execute`, {
      confirmSourceName: sqlConn.displayName,
      confirmTargetName: qa.displayName,
      acknowledgeWarnings: true,
    });
    await worker.drain(180_000);
    const delta = await api.get<MigrationRunDto>(`/api/runs/${started.id}`);
    expect(delta.updated).toBe(1);
    expect(delta.created).toBe(0);
  });

  it('validates the SQL source against the Dataverse target', async () => {
    const validation = await api.post<ValidationRunDto>('/api/validations', { migrationRunId: run.id });
    await worker.drain(180_000);
    const report = await api.get<ValidationRunDto>(`/api/validations/${validation.id}`);
    expect(report.status).toBe('COMPLETED');
    const region = report.entities.find((e) => e.logicalName === 'config.Region')!;
    expect(region.matched).toBeGreaterThan(0);
    expect(region.missing).toBe(0);
  });

  it('exports the cross-provider remediation package', async () => {
    const res = await t.app.inject({
      method: 'GET',
      url: `/api/plans/${plan.id}/issues-package.csv`,
      headers: { cookie: api.cookie },
    });
    expect(res.statusCode).toBe(200);
    expect(res.body.split('\r\n')[0]).toContain('Severity,Category,Table');
    expect(res.body).toContain('dbo.Customer');
  });
});
